env:
  node: true
extends: chomosuke
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: 'tsconfig.eslint.json'
plugins:
  - '@typescript-eslint'
ignorePatterns:
  - "build/**/*"
overrides:
  - files:
      - '**/*.test.ts'
    env:
      jest: true
    extends: 'chomosuke/jest'
    plugins:
      - jest
rules:
  no-console: off
